/* *****************************************************************************
 * This file has been generated by boschicon.js script.
 * DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
 *
 * source: Bosch-UI-Icon-1-5.zip
 * date: Thu, 10 Mar 2022 18:28:52 GMT
 **************************************************************************** */

const iconNames: string[] = [
  'alert-info',
  'alert-error',
  'alert-success',
  'alert-warning',
  'checkmark',
  'close',
  'close-small',
  'dot',
  'down',
  'indeterminate',
  'left',
  'inline-right',
  'inline-right-bold',
  'inline-list-checkmark',
  'inline-list-ul',
  'minus',
  'plus',
  'right',
  'search',
  'up',
  'up-down',
  'watch-off',
  'watch-on',
  'inline-externallink',
  'menu',
  'right-bold-small',
  'down-small',
  'left-small',
  'up-small',
  'right-small',
  'nosave-star-fill',
  'nosave-star-half',
  'nosave-star',
  'nosave-lr-externallink',
  'nosave-lr-right-small',
];

export default iconNames;
